version: '3.8'

services:
  build:
    build: .
    container_name: bos-builder
    volumes:
      - .:/bos
    command: make dist

  clean:
    build: .
    container_name: bos-cleaner
    volumes:
      - .:/bos
    command: make clean
